version: "3" 
# Defines which compose version to use
services:
  # Services line define which Docker images to run. In this case, it will be MySQL server and WordPress image.
  db:
    image: mysql:8.4.2
    container_name: mysql
    volumes:
      ["./data/mysql:/var/lib/mysql"]
    ports:
       - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin247#
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Admin247#

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      #PMA_USER: wordpress
      #PMA_PASSWORD: Admin247#
    ports:
      - "8080:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Admin247#
      WORDPRESS_DB_NAME: wordpress
    volumes:
      ["./data/html:/var/www/html"]